apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-deployment
  labels:
    app: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow
  template:
    metadata:
      labels:
        app: taskflow
    spec:
      containers:
      - name: taskflow
        image: <your-dockerhub-username>/taskflow-project:latest
        ports:
        - containerPort: 80
